default: &default
  adapter: postgresql
  encoding: unicode
  username: railsuser
  password: 123123
  host: localhost
  timeout: 5000
  pool: 5

development:
  <<: *default
  database: blog_app

test:
  <<: *default
  database: blog_app_test

production:
  <<: *default
  database: blog_app_production
