default: &default
  adapter: postgresql
  encoding: unicode
  username: rails_user
  password: 123123
  host: localhost
  timeout: 5000
  pool: 5

development:
  <<: *default
  database: final_app_development

test:
  <<: *default
  database: final_app_test

production:
  <<: *default
  database: final_app_production
